# Site settings
title: Carel de Jager
twitter_username: blockchainjag
name: Carel de Jager

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://booksandbeans.home.blog
 - title: GitHub
   url: https://github.com/blockchainjag
 - title: StackOverflow
   url: https://stackoverflow.com/users/11879770/carelkat
 - title: LinkedIn
   url: https://www.linkedin.com/in/careldejager/

#Any buzzword skills you want to include
skills:
 - Bitcoin Core
 - Ethereum
 - Hyperledger Fabric
 - Self-sovereign Identity
 - Solidity
 - JS
 - Technical Architecture
 - Machine learning
 - Power stations
 - Demand side management
 - Chemical Engineering

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://booksandbeans.home.blog/feed/?json=1
#https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Engineer
   start: 2014
   end: Ongoing
   employer: Eskom
   description: I work as a maintenance and operations engineer on a fossil fuel power plant of 3700MW capacity. I am the owner of the ash handling plant which produces 800kg of ash per second. The plant consists of 15km of conveying equipment, conditioners and stackers. My responsibility is to ensure that the plant is maintained and operated to specification.
 - title: Blockchain Consultant
   start: 2017
   end: Ongoing
   employer: The Blockchain Academy Pty Ltd
   description: I work as a consultant for the Blockchain Academy, facilitating a wide range of blockchain related training courses and presentations. Through the academy, I also deliver customised, industry-specific training to audiences ranging from the inexperienced to executive level.    I am also a public speaker, where I often illustrate my ability to explain technical use cases for blockchain technology in a simple and practical way. 

#Education is required
education:
 - level: Masters of Engineering (M. Eng)
   date: 2015
   subject: Engineering Management and Development
   school: North-West University
 - level: Bachelor of Engineering (B. Eng)
   date: 2013
   subject: Chemical Engineering
   school: North-West University


#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/1089dfe518c8ece7a88f164861aad808
   courses:
    - title: Cryptography I
      link: https://www.coursera.org/learn/crypto?
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/http://coursera-university-assets.s3.amazonaws.com/e8/7cc3d09d3f11e698dfff46d35f2da1/Stanford_Coursera_Logo.png?auto=format%2Ccompress&dpr=1&w=56px&h=56px&auto=format%2Ccompress&dpr=1&w=&h=
      description: An advanced course in applied cryptography
      date: February 28, 2019
      
bootcamp:
#   profileurl: https://www.godiive.com/wp-content/uploads/2018/08/Diive-logolarge-1024x522.png
   profileurl: img/Diive1.jpg
   courses:
    - title: Blockchain Bootcamp
      link: https://www.godiive.com/bootcamps/blockchain-bootcamp/
      optionalimage: https://www.godiive.com/wp-content/uploads/2018/08/Diive-logolarge-1024x522.png 
      description: The Diive Bootcamp description1 <br/><br/> Description 2 <br/><br/> Description 3 <br/><br/>
      date: June, 2019
 
#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/blockchainjag
   talks:
    - title: Rent Seeking in a Decentralised Economy
      speakerdeckId: b6e2b513a7cb47f9b3abcd5f5a3071bb
      conference: Finance Indaba October 2018, Johannesburg 2018
    - title: Blockchain’s Potential Role in Payment Modernization
      speakerdeckId: 42265ea2c4e347a1ac29753afa580e7d
      conference: Knowledge Hut Seminar July 2018, Johannesburg 2018

#List of interesting Github repo/projects to include - optional
github:
 #- https://github.com/blockchainjag/BlockchainJag.github.io
 - blockchainjag/SolidityPractice
 - blockchainjag/Lottery.sol
 - blockchainjag/hello-world
 - blockchainjag/BlockchainJag.github.io
 - blockchainjag/ticketsales.sol
 - blockchainjag/ERC20-Token-ICO
# - robhinds/opinionated-akka-http
# - robhinds/food2vec
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/genotype
# - robhinds/footweets
# - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am a chemical engineer on weekdays and a blockchain educator on weekends. <br/><br/>
  Line number 2. I enjoy building interesting products. <br/><br/>
  I am a Blockchain educator, engineer and international speaker for the Blockchain Academy, as well as an Operations & Maintenance engineer on the Ash Handling plant at a fossil fuel Power Station. I hold a BEng (Chemical) and MEng (Management) degree.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Articles</strong>: I enjoy writing articles about open blockchain platforms such as Bitcoin. Since I also work in the energy industry, Bitcoin's electricity usage is a subject <a target="_blank" href="https://medium.com/@careldj/bitcoin-mining-as-a-revenue-increasing-mechanism-for-eskom-407cd134b648"> that fascinates me. </a> I've written about <a target="_blank" href="https://medium.com/@careldj/a-review-of-the-power-requirements-for-a-bitcoin-majority-attack-c314c67eecb3"> the power requirements for a Bitcoin Majority attack </a>, <a target="_blank" href="https://medium.com/@careldj/bitcoin-mining-as-a-revenue-increasing-mechanism-for-eskom-407cd134b648"> using Bitcoin as a short term revenue fix </a> and <a target="_blank" href="https://medium.com/@careldj/bank-of-international-settlements-report-on-cryptocurrencies-critical-analysis-f3e811a6ddf6"> criticised the Bank of International Settlements view on Cryptocurrencies. </a> <br/><br/>
   <strong>Television</strong>: I have made two appearances on national television. In November 2017, I  <a target="_blank" href="https://youtu.be/Ahkk92GQ4Dc"> spoke about the value of Bitcoin </a>. The second time was in April 2018 about <a target="_blank" href="https://youtu.be/35UKi0ftCqY"> the basics of a decentralised currency </a>. <br/><br/>
   <strong>Personal</strong> I love hiking and try to do at least one multi-day hike per year. My personal favorites are the Fish river canyon in Namibia, the Otter trial in the Eastern Cape and the Wild Coast. I also play cricket and love long rides on my motorcycle. <br/><br/>
#   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)

#theme: jekyll-theme-minimal
